### ISSUE TITLE
Error reading adduct table

### ISSUE THREAD

**Issue by prasadpb** [coongroup/LipiDex#1]
hello team,

While executing Lipidex jar file I get this error "Error reading adduct table".
Can you please let me know 'What I am missing here?'

Thanks
Prasad

**Comment by phutch89** [comment]
Hi Prasad,

Thanks for giving LipiDex a try.  Could you send me the adduct table .csv found in your src/libraries folder for the library you were trying to load?

-Paul

**Comment by prasadpb** [comment]
Thanks Paul for quick response.

I am not sure if I got that far; as this is the first error I got before
opening the LipiDex


[image: Screen Shot 2018-05-02 at 14.42.15.png]

**Comment by phutch89** [comment]
Hi Prasad,

I cannot view the screenshot.  Could you try emailing it directly to lipidexcontact@gmail.com?

Thanks,
Paul

**Comment by phutch89** [comment]
Hi Prasad,
I downloaded the 1.0.1 release of LipiDex onto a different computer and did not receive this error.  Did you access LipiDex by cloning it, downloading the release, or downloading the repository? I want to make sure I am tracing exactly what you did.

Thanks,
Paul

**Comment by prasadpb** [comment]
Hi Paul, 
Same here, it worked on my Mac, but when I tried it few time times on Windows (Virtual Machine) getting same error repeatedly. Is it issue with Windows or VM?
Also, do you have step-by-step simple instructions on performing data analysis from QE+ raw data files?
Is compound discoverer processing required? can I use an output from Progenesis software?
It will be further interesting to see if LipiDex is useful for shotgun/ direct infusion data where we have just m/z and MS/MS data without chromatography.

Sorry for too many questions at once :)


Thanks
Prasad

**Comment by phutch89** [comment]
Hi Prasad,
Currently, LipiDex has been tested on Mac, Windows, and Windows Server.  I haven't tested it on a virtual machine and without knowing the specifics of your VM setup, I might not be able to replicate the problem.  

For data analysis instructions, I would refer you to the [LipiDex wiki](https://github.com/coongroup/LipiDex/wiki) or the [LipiDex Testing Procedures](https://github.com/coongroup/LipiDex/blob/master/LipiDex_Testing_Procedures.pdf).

LipiDex currently accepts feature tables from either Compound Discoverer or MZmine 2.  

Currently, we do not have plans to incorporate shotgun/direct infusion capabilities.  Although the Spectrum Searcher utility can match MS/MS spectra, it does not include the advanced functionality of programs like LipidXplorer for multi-dimensional shotgun lipidomics.

-Paul
