### ISSUE TITLE
Problems with Spectrum Searcher

### ISSUE THREAD

**Issue by mpadula** [coongroup/LipiDex#2]
Apologies if this is not the correct place to ask for help. I am a long time proteomics mass spectrometry person, but newbie with lipids. I have tried to use your software, but am having problems with the Spectrum Searcher. The data was generated on a QE+ and then processed with Compound Discoverer as per your tutorial. The raw files were then converted to mgf (have tried mzXML as well) and then submitted to Spectrum Searcher. Even with a single database selected, a csv file is never generated to input into the next step (Peak Finder). I'm not sure what I am doing wrong.

While the tutorials are some of the best I have seen, could I ask that an indication of the order be included? Of great use would be a single tutorial (for us complete noobs) that takes you from raw data to lipid identifications in the correct series of steps.

Cheers.

**Comment by phutch89** [comment]
Thanks for giving LipiDex a try and for looking through the tutorials.  If possible, could you send one of your MGF files to lipidexcontact@gmail.com? This would probably be the fastest way to resolve the issue.

Thanks,
Paul

**Comment by mpadula** [comment]
Sure Paul. But the example data isn't working either. The 3 Hap1 Positive and 3 Negative files were submitted. The Spectrum Searcher window has '50% - Creating Composite Library' and has been that way for more than an hour.

**Comment by phutch89** [comment]
For reference, this problem was solved by updating the user’s installation from 32-bit JRE to 64-bit JRE.
